# AppVeyor.com is a Continuous Integration service to build and run tests under
# Windows

environment:

  matrix:
    - PYTHON: "C:\\conda"
      MINICONDA_VERSION: "3.5.5"
      PYTHON_VERSION: "2.7"
      PYTHON_ARCH: "64"

install:
    # Install Python (from the official .msi of http://python.org) and pip when
    # not already installed.
    - "powershell ./anaconda-install.ps1"
    - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  
    # Check that we have the expected version and architecture for Python
    - "python --version"
  
    # Install the build and runtime dependencies of the project.
    - "conda update --yes conda"
    - "conda create --yes -n test -c astropy-ci-extras python=%PYTHON_VERSION%"
    - "conda install --yes numpy scipy matplotlib pandas requests beautiful-soup sqlalchemy pytest"
    - "conda update --yes astropy"

    # Install non-conda packages
    - "pip install suds"
    - "pip install sunpy"

# Not a .NET project, we build SunPy in the install step instead
build: false

test_script:
  # Change to a non-source folder to make sure we run the tests on the
  # installed library.
  - "SET PROJECT_DIR=%CD%"
  - "cd C:\\"

  # Skip joblib tests that require multiprocessing as they are prone to random
  # slow down
  - "python -c \"import sunpy sunpy.selftest()\""

