version: 2.1

no-backports: &no-backports
  name: Skip any branches called cherry-pick
  command: |
    if [[ "${CIRCLE_BRANCH}" == *"cherry-pick"* || "${CIRCLE_BRANCH}" == *"backport"* ]]; then
      circleci step halt
    fi

skip-check: &skip-check
  name: Check for [ci skip]
  command: bash .circleci/early_exit.sh

merge-check: &merge-check
  name: Check if we need to merge upstream master
  command: |
    if [[ -n "${CIRCLE_PR_NUMBER}" ]]; then
      git fetch origin --tags
      git fetch origin +refs/pull/$CIRCLE_PR_NUMBER/merge:pr/$CIRCLE_PR_NUMBER/merge
      git checkout -qf pr/$CIRCLE_PR_NUMBER/merge
    fi

apt-run: &apt-install
  name: Install apt packages
  command: |
    apt update
    apt install -y graphviz build-essential libopenjp2-7

jobs:
  twine-check:
    docker:
      - image: continuumio/miniconda3
    steps:
      - run: *no-backports
      - checkout
      - run: *skip-check
      - run: *merge-check
      - run: pip install -U pep517
      - run: python -m pep517.build --source .
      - run: python -m pip install -U --user --force-reinstall twine
      - run: python -m twine check dist/*

  pip-install:
    docker:
      - image: continuumio/miniconda3
    steps:
      - run: *no-backports
      - checkout
      - run: *skip-check
      - run: *merge-check
      - run: *apt-install
      - run: pip install -U pip
      - run: pip install --progress-bar off .[all,dev]
      - run: pip install -e .[all,dev]

  html-docs:
    docker:
      - image: continuumio/miniconda3
    environment:
      SUNPY_SAMPLEDIR=/root/sunpy/data/sample_data/
    steps:
      - run: *no-backports
      - checkout
      - run: *skip-check
      - restore_cache:
          keys: sample-data-v12
      - run: *merge-check
      - run: *apt-install
      - run: pip install -U tox tox-pypi-filter>=0.12
      - run: tox -e build_docs
      - save_cache:
          key: sample-data-v12
          paths:
            - /root/sunpy/data/sample_data/
      - run:
          name: Prepare for upload
          command: |
            # If it's not a PR, don't upload
            if [ -z "${CIRCLE_PULL_REQUEST}" ]; then
              rm -r docs/_build/html/*
            else
              # If it is a PR, delete sources, because it's a lot of files
              # which we don't really need to upload
              rm -r docs/_build/html/_sources
            fi
      - store_artifacts:
          path: docs/_build/html
      - run:
          name: "Built documentation is available at:"
          command: DOCS_URL="${CIRCLE_BUILD_URL}/artifacts/${CIRCLE_NODE_INDEX}/docs/_build/html/index.html"; echo $DOCS_URL

  figure:
    parameters:
      jobname:
        type: string
    docker:
      - image: continuumio/miniconda3
    environment:
      TOXENV=<< parameters.jobname >>
    steps:
      - run: *no-backports
      - checkout
      - run: *skip-check
      - run: *merge-check
      - run: *apt-install
      - run: pip install -U tox tox-conda codecov
      - run: tox
      - run: codecov
      - store_artifacts:
          path: .tmp/<< parameters.jobname >>/figure_test_images
      - run:
          name: "Image comparison page is available at: "
          command: echo "${CIRCLE_BUILD_URL}/artifacts/${CIRCLE_NODE_INDEX}/.tmp/${TOXENV}/figure_test_images/fig_comparison.html"
      - persist_to_workspace:
          root: .tmp/
          paths: << parameters.jobname >>/figure_test_images

  deploy-reference-images:
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      - attach_workspace:
          at: .tmp
      - run: ls -la .tmp/
      #- run: git clone https://github.com/sunpy/sunpy-figure-tests.git -b sunpy-${CIRCLE_BRANCH} ~/sunpy-figure-tests/
      - run: git clone https://github.com/sunpy/sunpy-figure-tests.git -b sunpy-test ~/sunpy-figure-tests/
      - run: cp -r .tmp/figure_py36/figure_test_images/*.png ~/sunpy-figure-tests/figures/figure_py36/
      - run: cp -r .tmp/figure_py37_astropydev/figure_test_images/*.png ~/sunpy-figure-tests/figures/figure_py37_astropydev/

workflows:
  version: 2

  packaging:
    jobs:
      - twine-check
      - pip-install

  figure-tests:
    jobs:
      - figure:
          name: << matrix.jobname >>
          matrix:
            parameters:
              jobname:
                - "figure_py36"
                - "figure_py37_astropydev"

      - deploy-reference-images:
          requires:
            - "figure_py36"
            - "figure_py37_astropydev"

  test-documentation:
    jobs:
      - html-docs

notify:
  webhooks:
    - url: https://giles.cadair.dev/circleci
