name: extra

on:
  push:
  pull_request:
    # We also want this workflow triggered if the 'Extra CI' label is added
    # The first three are the defaults
    types:
      - opened
      - synchronized
      - reopened
      - labeled

jobs:
  cron_tests:
    if: contains(github.event.pull_request.labels.*.name, 'Extra CI')
    strategy:
      fail-fast: false
      matrix:
        include:
          - toxenv: py38-hypothesis
            os: ubuntu-latest
            python: 3.8

          - toxenv: py38-devdeps
            os: ubuntu-latest
            python: 3.8

    name: 'tox'
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Install Graphviz and openjpeg
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get install -y libopenjp2-7 graphviz

      - name: Install Tox
        run: python -m pip install --upgrade tox

      - name: Run Tox
        run: tox ${{ matrix.toxargs }} -e ${{ matrix.toxenv }} -- ${{ matrix.toxposargs }}
